Reference states sanctions body Cordapp Migrated to 4.12-RC01 and JDK17
corda/samples-kotlin pull request #96
Opened 2024-05-28 15:04 UTC by ashwani-r3

2024-05-28 15:11 UTC, adelel1 commented on Features/constants.properties
> +cordaCoreVersion=4.12-RC01
This can be RC02 now

2024-05-28 15:20 UTC, jakubzadroga requested changes
Two comments please

2024-05-28 15:20 UTC, jakubzadroga commented on Features/referenceStates-sanctionsBody/build.gradle
> +        testJvmFxArgs = [  '--add-exports', 'java.base/sun.nio.ch=ALL-UNNAMED',
Is this needed? Can't see it used anywhere in this CorDapp

2024-05-28 15:20 UTC, jakubzadroga commented on Features/referenceStates-sanctionsBody/build.gradle
>      cordaDriver "net.corda:corda-shell:4.9"
The 4.9 shell will fail on 4.12 node, please update to `cordaDriver "net.corda:corda-shell:$corda_release_version"
`

2024-05-29 07:05 UTC, jakubzadroga approved these changes
LGTM

2024-05-29 08:08 UTC, merged